version: '3.1'

services:
  postgresql-master:
    container_name: postgresql-master
    image: docker.io/bitnami/postgresql:14
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_password
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: frankit

  postgresql-slave:
    container_name: postgresql-slave
    image: docker.io/bitnami/postgresql:14
    ports:
      - "5436:5432"
    depends_on:
      - postgresql-master
    environment:
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_password
      POSTGRESQL_MASTER_HOST: postgresql-master
      POSTGRESQL_PASSWORD: test
      POSTGRESQL_MASTER_PORT_NUMBER: 5432
      ALLOW_EMPTY_PASSWORD: yes
    restart: always

volumes:
  postgres-data:
    driver: local